/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2019 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "isr_TIMER.h"
#include "UART.h"
#include "timer_clock.h"
#include "Timer.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C_Master.h"
#include "I2C_Master_PVT.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "CS_aliases.h"
#include "CS.h"
#include "Red_LED_aliases.h"
#include "Red_LED.h"
#include "isr_UART.h"
#include "Temperature_Sensor_aliases.h"
#include "Temperature_Sensor.h"
#include "ADC_DelSig.h"
#include "isr_FIFO.h"
#include "INT_LIS3DH_aliases.h"
#include "INT_LIS3DH.h"
#include "UART_IntClock.h"
#include "SPIM_IntClock.h"
#include "ADC_DelSig_AMux.h"
#include "ADC_DelSig_Ext_CP_Clk.h"
#include "ADC_DelSig_IRQ.h"
#include "ADC_DelSig_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

